name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FLUTTER_VERSION: '3.16.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 缓存Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-
      
      - name: 缓存pub依赖
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-
      
      - name: 设置Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: 调试环境
        run: |
          flutter doctor -v
          flutter --version
      
      - name: 获取依赖
        id: pub-get
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (1)
        if: steps.pub-get.outcome == 'failure'
        id: pub-get-retry-1
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (2)
        if: steps.pub-get-retry-1.outcome == 'failure'
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 检查代码格式
        run: flutter format --set-exit-if-changed .
      
      - name: 分析代码
        run: flutter analyze
      
      - name: 运行测试
        run: flutter test

  build-android:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: 缓存Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-
      
      - name: 缓存Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      - name: 缓存pub依赖
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-
      
      - name: 设置Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: 获取依赖
        id: android-pub-get
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (1)
        if: steps.android-pub-get.outcome == 'failure'
        id: android-pub-get-retry-1
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (2)
        if: steps.android-pub-get-retry-1.outcome == 'failure'
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 构建APK
        run: flutter build apk --release
        timeout-minutes: 15
      
      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: photo-gallery-v${{ github.run_number }}-flutter-${{ env.FLUTTER_VERSION }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 14
          
  build-web:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 缓存Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-linux-stable-${{ env.FLUTTER_VERSION }}-${{ runner.os }}-
      
      - name: 缓存pub依赖
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-
      
      - name: 设置Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: 获取依赖
        id: web-pub-get
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (1)
        if: steps.web-pub-get.outcome == 'failure'
        id: web-pub-get-retry-1
        continue-on-error: true
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 重试获取依赖 (2)
        if: steps.web-pub-get-retry-1.outcome == 'failure'
        run: flutter pub get
        timeout-minutes: 5
      
      - name: 构建Web
        run: flutter build web --release
        timeout-minutes: 10
      
      - name: 上传Web构建
        uses: actions/upload-artifact@v4
        with:
          name: web-build-v${{ github.run_number }}-flutter-${{ env.FLUTTER_VERSION }}
          path: build/web/
          retention-days: 14 