name: 发布版本

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: 设置Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true
      
      - name: 获取依赖
        run: flutter pub get
      
      - name: 构建APK
        run: flutter build apk --release
      
      - name: 构建Web
        run: flutter build web --release
      
      - name: 打包Web构建
        run: cd build/web && zip -r ../../web-build.zip .
      
      - name: 创建发布并上传资源
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: 版本 ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            web-build.zip 